const allSector = [
  { value: "1", name: "Manufacturing", parentId: "0" },
  {
    value: "19",
    name: "Construction materials",
    parentId: "1",
  },
  {
    value: "18",
    name: "Electronics and Optics",
    parentId: "1",
  },
  { value: "6", name: "Food and Beverage", parentId: "1" },
  {
    value: "342",
    name: "Bakery & confectionery products",
    parentId: "6",
  },
  { value: "43", name: "Beverages", parentId: "6" },
  {
    value: "42",
    name: "Fish & fish products",
    parentId: "6",
  },
  {
    value: "40",
    name: "Meat & meat products",
    parentId: "6",
  },
  {
    value: "39",
    name: "Milk & dairy products",
    parentId: "6",
  },
  { value: "437", name: "Other", parentId: "6" },
  {
    value: "378",
    name: "Sweets & snack food",
    parentId: "6",
  },
  { value: "13", name: "Furniture", parentId: "1" },
  { value: "389", name: "Bathroom/sauna ", parentId: "13" },
  { value: "385", name: "Bedroom", parentId: "13" },
  { value: "390", name: "Children's room ", parentId: "13" },
  { value: "98", name: "Kitchen ", parentId: "13" },
  { value: "101", name: "Living room ", parentId: "13" },
  { value: "392", name: "Office", parentId: "13" },
  { value: "394", name: "Other (Furniture)", parentId: "13" },
  { value: "341", name: "Outdoor ", parentId: "13" },
  { value: "99", name: "Project furniture", parentId: "13" },
  { value: "12", name: "Machinery", parentId: "1" },
  { value: "94", name: "Machinery components", parentId: "12" },
  { value: "91", name: "Machinery equipment/tools", parentId: "12" },
  {
    value: "224",
    name: "Manufacture of machinery ",
    parentId: "12",
  },
  { value: "97", name: "Maritime", parentId: "12" },
  {
    value: "271",
    name: "Aluminium and steel workboats",
    parentId: "97",
  },
  { value: "269", name: "Boat/Yacht building", parentId: "97" },
  {
    value: "230",
    name: "Ship repair and conversion",
    parentId: "97",
  },
  { value: "93", name: "Metal structures", parentId: "12" },
  { value: "508", name: "Other", parentId: "12" },
  {
    value: "227",
    name: "Repair and maintenance service",
    parentId: "12",
  },
  { value: "11", name: "Metalworking", parentId: "1" },
  {
    value: "67",
    name: "Construction of metal structures",
    parentId: "11",
  },
  { value: "263", name: "Houses and buildings", parentId: "11" },
  { value: "267", name: "Metal products", parentId: "11" },
  { value: "542", name: "Metal works", parentId: "11" },
  { value: "75", name: "CNC-machining", parentId: "542" },
  { value: "62", name: "Forgings, Fasteners ", parentId: "542" },
  {
    value: "69",
    name: "Gas, Plasma, Laser cutting",
    parentId: "542",
  },
  {
    value: "66",
    name: "MIG, TIG, Aluminum welding",
    parentId: "542",
  },
  { value: "9", name: "Plastic and Rubber", parentId: "1" },
  { value: "54", name: "Packaging", parentId: "9" },
  { value: "556", name: "Plastic goods", parentId: "9" },
  {
    value: "559",
    name: "Plastic processing technology",
    parentId: "9",
  },
  {
    value: "55",
    name: "Blowing",
    parentId: "559",
  },
  {
    value: "57",
    name: "Moulding",
    parentId: "559",
  },
  {
    value: "53",
    name: "Plastics welding and processing",
    parentId: "559",
  },
  {
    value: "560",
    name: "Plastic profiles",
    parentId: "9",
  },
  { value: "5", name: "Printing ", parentId: "1" },
  { value: "148", name: "Advertising", parentId: "5" },
  { value: "150", name: "Book/Periodicals printing", parentId: "5" },
  {
    value: "145",
    name: "Labelling and packaging printing",
    parentId: "5",
  },
  { value: "7", name: "Textile and Clothing", parentId: "1" },
  { value: "44", name: "Clothing", parentId: "7" },
  { value: "45", name: "Textile", parentId: "7" },
  { value: "8", name: "Wood", parentId: "1" },
  { value: "337", name: "Other (Wood)", parentId: "8" },
  { value: "51", name: "Wooden building materials", parentId: "8" },
  { value: "47", name: "Wooden houses", parentId: "8" },
  { value: "2", name: "Service", parentId: "0" },
  { value: "25", name: "Business services", parentId: "2" },
  { value: "35", name: "Engineering", parentId: "2" },
  {
    value: "28",
    name: "Information Technology and Telecommunications",
    parentId: "2",
  },
  {
    value: "581",
    name: "Data processing, Web portals, E-marketing",
    parentId: "28",
  },
  {
    value: "576",
    name: "Programming, Consultancy",
    parentId: "28",
  },
  {
    value: "121",
    name: "Software, Hardware",
    parentId: "28",
  },
  {
    value: "122",
    name: "Telecommunications",
    parentId: "28",
  },
  { value: "22", name: "Tourism", parentId: "2" },
  { value: "141", name: "Translation services", parentId: "2" },
  { value: "21", name: "Transport and Logistics", parentId: "2" },
  { value: "111", name: "Air", parentId: "21" },
  { value: "114", name: "Rail", parentId: "21" },
  { value: "112", name: "Road", parentId: "21" },
  { value: "113", name: "Water", parentId: "21" },
  { value: "3", name: "Other", parentId: "0" },
  { value: "37", name: "Creative industries", parentId: "3" },
  { value: "29", name: "Energy technology", parentId: "3" },
  { value: "33", name: "Environment", parentId: "3" },
];
export default allSector;
